export const AUTH = "AUTH";
export const ALERT = "ALERT";
export const HISTORY = {
    CREATE_HISTORY: "CREATE_HISTORY",
    GET_ALL_HISTORY: "GET_ALL_HISTORY",
};
export const QUIZ = {
    CREATE_QUIZ: "CREATE_QUIZ",
    LOADING_QUIZ: "LOADING_QUIZ",
    GET_QUIZS: "GET_QUIZS",
    UPDATE_QUIZ: "UPDATE_QUIZ",
    GET_QUIZ: "GET_QUIZ",
    DELETE_QUIZ: "DELETE_QUIZ",
};
export const FLASHCARD = {
    CREATE_FLASHCARD: "CREATE_FLASHCARD",
    LOADING_FLASHCARD: "LOADING_FLASHCARD",
    GET_FLASHCARDS: "GET_FLASHCARDS",
    UPDATE_FLASHCARD: "UPDATE_FLASHCARD",
    GET_FLASHCARD: "GET_FLASHCARD",
    DELETE_FLASHCARD: "DELETE_FLASHCARD",
};
